#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral LMB_BRAM_IF_CNTLR_0 */
#define XPAR_LMB_BRAM_IF_CNTLR_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_LMB_BRAM_IF_CNTLR_0_BASEADDR 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_HIGHADDR 0xffff
#define XPAR_LMB_BRAM_IF_CNTLR_0_DATA_WIDTH 0x20
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_FAULT_INJECT 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_CE_FAILING_REGISTERS 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_UE_FAILING_REGISTERS 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_LMB_BRAM_IF_CNTLR_0_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral LMB_BRAM_IF_CNTLR_0 */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0xffff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_INTC_0 */
#define XPAR_AXI_INTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_AXI_INTC_0_BASEADDR 0x41200000
#define XPAR_AXI_INTC_0_HIGHADDR 0x4120ffff
#define XPAR_AXI_INTC_0_KIND_OF_INTR 0x0
#define XPAR_AXI_INTC_0_IS_FAST 0x0
#define XPAR_AXI_INTC_0_IVAR_RST_VAL 0x10
#define XPAR_AXI_INTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_AXI_INTC_0_ADDR_WIDTH 0x20
#define XPAR_AXI_INTC_0_NUM_SW_INTR 0x0
#define XPAR_AXI_INTC_0_HAS_IVR 0x1
#define XPAR_AXI_INTC_0_HAS_CIE 0x1
#define XPAR_AXI_INTC_0_HAS_SIE 0x1
#define XPAR_AXI_INTC_0_HAS_IPR 0x1

/* Canonical definitions for peripheral AXI_INTC_0 */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x0
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x0
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_0_BASEADDR 0x41c00000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41c0ffff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x2faf080
#define XPAR_AXI_TIMER_0_INTERRUPTS 0x2001
#define XPAR_FABRIC_AXI_TIMER_0_INTR 1
#define XPAR_AXI_TIMER_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c00000
#define XPAR_FABRIC_XTMRCTR_0_INTR 1
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c0ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x2faf080
#define XPAR_XTMRCTR_0_INTERRUPTS 0x2001
#define XPAR_XTMRCTR_0_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral E_UART_0 */
#define XPAR_E_UART_0_BASEADDR 0x44a00000
#define XPAR_E_UART_0_HIGHADDR 0x44a0ffff

/* Definitions for peripheral HYPERBUS_CONTROLLER_0 */
#define XPAR_HYPERBUS_CONTROLLER_0_BASEADDR 0x10000
#define XPAR_HYPERBUS_CONTROLLER_0_HIGHADDR 0x1ffff

/*  BOARD definition */
#define XPS_BOARD_SCU35

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_RISCV_TIMEBASE_FREQUENCY 50000000
#define XPAR_MICROBLAZE_RISCV_FREQ 50000000
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 1
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 1
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 2
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 1
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_D_CACHE_SIZE 4096
#define XPAR_MICROBLAZE_RISCV_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_D_CACHE_BASEADDR 2147483648
#define XPAR_MICROBLAZE_RISCV_D_CACHE_HIGHADDR 2155872255
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_REG 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 50000000

#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 1

#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 4096

#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 1

#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 4096

#define XPAR_MICROBLAZE_RISCV_USE_FPU 0

#define XPAR_MICROBLAZE_RISCV_USE_MMU 0

#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0

#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0

#define XPAR_MICROBLAZE_RISCV_D_LMB 1

#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0

#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

#define XPAR_MICROBLAZE_RISCV_ADDR_SIZE 32

/* Device ID */
#define XPAR_DEVICE_ID "xcsu35p"

#endif  /* end of protection macro */