#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Script generated by Vivado on Thu Mar 05 17:15:06 PST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : hyperbus_controller_tb.sh
# Simulator    : AMD Vivado Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : hyperbus_controller_tb.sh
#                hyperbus_controller_tb.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                hyperbus_controller_tb.sh [-rerun]
#                hyperbus_controller_tb.sh [-reset_run]
#                hyperbus_controller_tb.sh [-clean]
#                hyperbus_controller_tb.sh [-reset_log]
#                hyperbus_controller_tb.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
#**********************************************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# script location helpers
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
sim_run_name="${SIM_RUN_NAME:-usplus}"
sim_run_dir="${SIM_RUN_DIR:-$script_dir/runs/$sim_run_name}"
cmd_tcl_path="$script_dir/cmd.tcl"
vlog_prj_path="$sim_run_dir/vlog.prj"

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/tools/Xilinx/${SIM_VER_XSIM}/data"

# set xvlog options
tb_xvlog_defines="${TB_XVLOG_DEFINES:-}"
xvlog_opts="--incr --relax  -L uvm ${tb_xvlog_defines}"

# simulation root library directory
sim_lib_dir="xsim.dir"

# script info
echo -e "hyperbus_controller_tb.sh - Script generated by export_simulation (Vivado v2025.2 (64-bit)-id)\n"
echo -e "INFO: Simulation run name: ${sim_run_name}\n"
echo -e "INFO: Simulation run directory: ${sim_run_dir}\n"
if [[ -n "${tb_xvlog_defines}" ]]; then
  echo -e "INFO: Applying TB compile defines: ${tb_xvlog_defines}\n"
fi

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./hyperbus_controller_tb.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xvlog $xvlog_opts -prj "$vlog_prj_path" 2>&1 | tee compile.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  xelab --incr --debug typical --relax --mt 8  -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot hyperbus_controller_tb xil_defaultlib.hyperbus_controller_tb xil_defaultlib.glbl -log elaborate.log
}

# RUN_STEP: <simulate>
simulate()
{
  xsim hyperbus_controller_tb -key {Behavioral:sim_1:Functional:hyperbus_controller_tb} -tclbatch "$cmd_tcl_path" -log simulate.log
  awk '/\[[^]]*FIFO\]/' simulate.log > simulate_fifo.log
}

ensure_run_dir()
{
  mkdir -p "$sim_run_dir"
  cd "$sim_run_dir"
}

write_vlog_prj()
{
  cat > "$vlog_prj_path" <<EOF
verilog xil_defaultlib -i "/tools/Xilinx/2025.2/data/rsb/busdef" \
"$repo_root/infinion/002-26518_0B/s27kl0642.v" \

sv xil_defaultlib -i "/tools/Xilinx/2025.2/data/rsb/busdef" -i "$repo_root/tb" \
"$repo_root/rtl/hyperbus_fifo_bank_xilinx.sv" \
"$repo_root/rtl/hyperbus_phy_xilinx.sv" \
"$repo_root/rtl/hyperbus_phy_xilinx_usplus.sv" \
"$repo_root/rtl/hyperbus_phy_xilinx_7series.sv" \
"$repo_root/rtl/hyperbus_axi_lite_frontend.sv" \
"$repo_root/rtl/hyperbus_axi_full_frontend.sv" \
"$repo_root/rtl/hyperbus_hb_engine.sv" \
"$repo_root/rtl/hyperbus_controller.sv" \
"$repo_root/tb/hyperbus_controller_tb.sv" \

verilog xil_defaultlib "$script_dir/glbl.v"

# Do not sort compile order
nosort
EOF
}

# STEP: setup
setup()
{
  ensure_run_dir

  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

  # delete previous design library generated data
  if [[ ($b_clean == 1) ]]; then
    clean
    echo -e "INFO: Design library generated data deleted.\n"
    exit 0
  fi

  # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>
  # Prefer precompiled XSIM libraries if available and no explicit
  # -lib_map_path is provided. Priority:
  #   1) repo-local simlibs/ (checked into workspace)
  #   2) ~/.xilinx_simlibs (user cache)
  if [[ ($lib_map_path == "") && (-d "$repo_root/simlibs") ]]; then
    lib_map_path="$repo_root/simlibs"
    echo -e "INFO: Using precompiled simulation libraries at: $lib_map_path\n"
  elif [[ ($lib_map_path == "") && (-d "$HOME/.xilinx_simlibs") ]]; then
    lib_map_path="$HOME/.xilinx_simlibs"
    echo -e "INFO: Using precompiled simulation libraries at: $lib_map_path\n"
  fi

}

# simulator index file/library directory processing
init_lib()
{
  write_vlog_prj

  if [[ ($b_rerun == 1) ]]; then
    # keep previous state for incremental run
    return 0
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # keep previous simulator index file
    true
  else
    # copy simulator index file to current directory
    copy_setup_file
  fi

  if [[ ($lib_map_path != "") ]]; then
    ref_lib_dir=$lib_map_path
  fi
}

# copy xsim.ini file
copy_setup_file()
{
  file="xsim.ini"
  local default_map_path

  default_map_path="/tools/Xilinx/${SIM_VER_XSIM}/data/xsim"

  if [[ ($lib_map_path != "") ]]; then
    src_file="$lib_map_path/$file"
    if [[ -e $src_file ]]; then
      # Precompiled library directory already provides xsim.ini.
      cp $src_file .
    elif [[ -e "$default_map_path/$file" ]]; then
      # Use Vivado template xsim.ini, then remap known libs to precompiled path.
      cp "$default_map_path/$file" .
      apply_precompiled_mappings "$lib_map_path"
    fi
  elif [[ -e "$default_map_path/$file" ]]; then
    cp "$default_map_path/$file" .
  fi

  # map local design libraries to xsim.ini
  map_local_libs
}

# remap xsim.ini libraries to precompiled library directories when available
apply_precompiled_mappings()
{
  local precomp_dir="$1"
  local file="xsim.ini"
  local file_tmp="xsim.ini.precomp.tmp"

  if [[ ! -d "$precomp_dir" ]] || [[ ! -e "$file" ]]; then
    return
  fi

  rm -f "$file_tmp"
  while read -r line
  do
    IN=$line

    # Keep comments/empty lines unchanged.
    if [[ -z "$IN" ]] || [[ "$IN" == \#* ]]; then
      echo "$IN" >> "$file_tmp"
      continue
    fi

    # split mapping entry with '=' delimiter to fetch library name and mapping
    read lib_name mapping <<<$(IFS="="; echo $IN)

    if [[ -d "$precomp_dir/$lib_name" ]]; then
      echo "$lib_name=$precomp_dir/$lib_name" >> "$file_tmp"
    else
      echo "$IN" >> "$file_tmp"
    fi
  done < "$file"

  mv "$file_tmp" "$file"
}

# map local design libraries
map_local_libs()
{
  updated_mappings=()
  local_mappings=()

  # local design libraries
  local_libs=()

  if [[ 0 == ${#local_libs[@]} ]]; then
    return
  fi

  file="xsim.ini"
  file_backup="xsim.ini.bak"

  if [[ -e $file ]]; then
    rm -f $file_backup

    # create a backup copy of the xsim.ini file
    cp $file $file_backup

    # read libraries from backup file and search in local library collection
    while read -r line
    do
      IN=$line

      # split mapping entry with '=' delimiter to fetch library name and mapping
      read lib_name mapping <<<$(IFS="="; echo $IN)

      # if local library found, then construct the local mapping and add to local mapping collection
      if `echo ${local_libs[@]} | grep -wq $lib_name` ; then
        line="$lib_name=xsim.dir/$lib_name"
        local_mappings+=("$lib_name")
      fi

      # add to updated library mapping collection
      updated_mappings+=("$line")
    done < "$file_backup"

    # append local libraries not found originally from xsim.ini
    for (( i=0; i<${#local_libs[*]}; i++ )); do
      lib_name="${local_libs[i]}"

      if [[ (${#local_mappings[@]} -eq 0) ]] ; then
        line="$lib_name=xsim.dir/$lib_name"
        updated_mappings+=("$line")
      elif `echo ${local_mappings[@]} | grep -wvq $lib_name` ; then
        line="$lib_name=xsim.dir/$lib_name"
        updated_mappings+=("$line")
      fi
    done

    # write updated mappings in xsim.ini
    rm -f $file
    for (( i=0; i<${#updated_mappings[*]}; i++ )); do
      lib_name="${updated_mappings[i]}"
      echo $lib_name >> $file
    done
  else
    for (( i=0; i<${#local_libs[*]}; i++ )); do
      lib_name="${local_libs[i]}"
      mapping="$lib_name=xsim.dir/$lib_name"
      echo $mapping >> $file
    done
  fi
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xelab.pb xsim.jou xvhdl.log xvlog.log compile.log elaborate.log simulate.log simulate_fifo.log xelab.log xsim.log run.log xvhdl.pb xvlog.pb hyperbus_controller_tb.wdb xsim.dir libdpi.so xsim.ini xsim.ini.bak xsim.ini.precomp.tmp vlog.prj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated design library data from the previous run
clean()
{
  files_to_remove=("${design_libs[@]}")
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="$sim_lib_dir/${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  # delete design library directory
  rm -rf $sim_lib_dir
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xvhdl.log xvlog.log compile.log elaborate.log simulate.log simulate_fifo.log xelab.log xsim.log run.log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./hyperbus_controller_tb.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -rerun)         b_rerun=1         ;;
      -reset_run)     b_reset_run=1     ;;
      -clean)         b_clean=1         ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -clean is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_clean == 1) ]]; then
    echo -e "ERROR: -clean switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: hyperbus_controller_tb.sh [-help]\n\
Usage: hyperbus_controller_tb.sh [-step]\n\
Usage: hyperbus_controller_tb.sh [-lib_map_path]\n\
Usage: hyperbus_controller_tb.sh [-rerun]\n\
Usage: hyperbus_controller_tb.sh [-reset_run]\n\
Usage: hyperbus_controller_tb.sh [-clean]\n\
Usage: hyperbus_controller_tb.sh [-reset_log]\n\
Usage: hyperbus_controller_tb.sh [-keep_index]\n\
Usage: hyperbus_controller_tb.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-rerun] -- Rerun step(s) in incremental mode (data generated from the previous run will be retained).\n\
To rerun a specific step, pass the -step <name> switch in addition to -rerun switch.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-clean] -- Delete simulator generated design library data from the previous run. This switch will not\n\
execute steps defined in the script.\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_rerun=0
b_reset_run=0
b_clean=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
