domain_path: /raid/work/hyperbus_controller_freertos_port/vitis_ws4/platform/export/platform/sw/standalone_microblaze_0
app_src_dir: /raid/work/hyperbus_controller_freertos_port/vitis_ws4/hello_world/src
template: empty_application
lang: c
