#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral LMB_BRAM_IF_CNTLR_0 */
#define XPAR_LMB_BRAM_IF_CNTLR_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_LMB_BRAM_IF_CNTLR_0_BASEADDR 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_HIGHADDR 0x7fff
#define XPAR_LMB_BRAM_IF_CNTLR_0_DATA_WIDTH 0x20
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_FAULT_INJECT 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_CE_FAILING_REGISTERS 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_UE_FAILING_REGISTERS 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_LMB_BRAM_IF_CNTLR_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_LMB_BRAM_IF_CNTLR_0_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral LMB_BRAM_IF_CNTLR_0 */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0x7fff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XCSUDMA_NUM_INSTANCES 1

/* Definitions for peripheral PMCBRIDGE_0_PMCL_DMA_0 */
#define XPAR_PMCBRIDGE_0_PMCL_DMA_0_COMPATIBLE "xlnx,pmcl-dma-11.0"
#define XPAR_PMCBRIDGE_0_PMCL_DMA_0_BASEADDR 0x40e0000
#define XPAR_PMCBRIDGE_0_PMCL_DMA_0_HIGHADDR 0x40effff
#define XPAR_PMCBRIDGE_0_PMCL_DMA_0_DMA_TYPE 0x1

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_DMA_0 */
#define XPAR_XCSUDMA_0_BASEADDR 0x40e0000
#define XPAR_XCSUDMA_0_HIGHADDR 0x40effff
#define XPAR_XCSUDMA_0_COMPATIBLE "xlnx,pmcl-dma-11.0"
#define XPAR_XCSUDMA_0_DMA_TYPE 0x1

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_INTC_0 */
#define XPAR_AXI_INTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_AXI_INTC_0_BASEADDR 0x41200000
#define XPAR_AXI_INTC_0_HIGHADDR 0x4120ffff
#define XPAR_AXI_INTC_0_KIND_OF_INTR 0x4
#define XPAR_AXI_INTC_0_IS_FAST 0x0
#define XPAR_AXI_INTC_0_IVAR_RST_VAL 0x10
#define XPAR_AXI_INTC_0_NUM_INTR_INPUTS 0x3
#define XPAR_AXI_INTC_0_ADDR_WIDTH 0x20
#define XPAR_AXI_INTC_0_NUM_SW_INTR 0x0
#define XPAR_AXI_INTC_0_HAS_IVR 0x1
#define XPAR_AXI_INTC_0_HAS_CIE 0x1
#define XPAR_AXI_INTC_0_HAS_SIE 0x1
#define XPAR_AXI_INTC_0_HAS_IPR 0x1

/* Canonical definitions for peripheral AXI_INTC_0 */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x0
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x4
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x3
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XOSPIPSV_NUM_INSTANCES 1

/* Definitions for peripheral PMCBRIDGE_0_PMCL_OSPI_0 */
#define XPAR_PMCBRIDGE_0_PMCL_OSPI_0_COMPATIBLE "xlnx,pmc-ospi-11.0"
#define XPAR_PMCBRIDGE_0_PMCL_OSPI_0_BASEADDR 0x4090000
#define XPAR_PMCBRIDGE_0_PMCL_OSPI_0_HIGHADDR 0x409ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_OSPI_0 */
#define XPAR_XOSPIPSV_0_BASEADDR 0x4090000
#define XPAR_XOSPIPSV_0_HIGHADDR 0x409ffff
#define XPAR_XOSPIPSV_0_COMPATIBLE "xlnx,pmc-ospi-11.0"

#define XPAR_XSPI_NUM_INSTANCES 1

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44a00000
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44a0ffff
#define XPAR_AXI_QUAD_SPI_0_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_0_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_0_BITS_PER_WORD 0x8
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 0x2
#define XPAR_AXI_QUAD_SPI_0_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_STARTUP_BLOCK 0x1
#define XPAR_AXI_QUAD_SPI_0_FIFO_SIZE 0x100
#define XPAR_AXI_QUAD_SPI_0_INTERRUPTS 0x2
#define XPAR_FABRIC_AXI_QUAD_SPI_0_INTR 2
#define XPAR_AXI_QUAD_SPI_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x0
#define XPAR_XSPI_0_BASEADDR 0x44a00000
#define XPAR_FABRIC_XSPI_0_INTR 2
#define XPAR_XSPI_0_HIGHADDR 0x44a0ffff
#define XPAR_XSPI_0_AXI_INTERFACE 0x0
#define XPAR_XSPI_0_BITS_PER_WORD 0x8
#define XPAR_XSPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_0_FIFO_SIZE 0x100
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_INTERRUPTS 0x2
#define XPAR_XSPI_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_0_NUM_SS_BITS 0x1
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x2
#define XPAR_XSPI_0_STARTUP_BLOCK 0x1
#define XPAR_XSPI_0_XIP_MODE 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_0_BASEADDR 0x41c00000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41c0ffff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x2faf080
#define XPAR_AXI_TIMER_0_INTERRUPTS 0x2001
#define XPAR_FABRIC_AXI_TIMER_0_INTR 1
#define XPAR_AXI_TIMER_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c00000
#define XPAR_FABRIC_XTMRCTR_0_INTR 1
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c0ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x2faf080
#define XPAR_XTMRCTR_0_INTERRUPTS 0x2001
#define XPAR_XTMRCTR_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XTRNGPSX_NUM_INSTANCES 1

/* Definitions for peripheral PMCBRIDGE_0_PMCL_TRNG_0 */
#define XPAR_PMCBRIDGE_0_PMCL_TRNG_0_COMPATIBLE "xlnx,pmcl-trng-11.0"
#define XPAR_PMCBRIDGE_0_PMCL_TRNG_0_BASEADDR 0x4120000
#define XPAR_PMCBRIDGE_0_PMCL_TRNG_0_HIGHADDR 0x412ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_TRNG_0 */
#define XPAR_XTRNGPSX_0_BASEADDR 0x4120000
#define XPAR_XTRNGPSX_0_HIGHADDR 0x412ffff
#define XPAR_XTRNGPSX_0_COMPATIBLE "xlnx,pmcl-trng-11.0"

/* Definitions for peripheral E_UART_0 */
#define XPAR_E_UART_0_BASEADDR 0x44a10000
#define XPAR_E_UART_0_HIGHADDR 0x44a1ffff

/* Definitions for peripheral HYPERBUS_CONTROLLER_0 */
#define XPAR_HYPERBUS_CONTROLLER_0_BASEADDR 0x10000
#define XPAR_HYPERBUS_CONTROLLER_0_HIGHADDR 0x1ffff

/* Definitions for peripheral PMCBRIDGE_0_CCU_APB_0 */
#define XPAR_PMCBRIDGE_0_CCU_APB_0_BASEADDR 0x4130000
#define XPAR_PMCBRIDGE_0_CCU_APB_0_HIGHADDR 0x413ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_CCU_APB_0 */
#define XPAR_CCU_APB_0_BASEADDR 0x4130000
#define XPAR_CCU_APB_0_HIGHADDR 0x413ffff

/* Definitions for peripheral PMCBRIDGE_0_CCU_RD_STREAM_0 */
#define XPAR_PMCBRIDGE_0_CCU_RD_STREAM_0_BASEADDR 0x4060000
#define XPAR_PMCBRIDGE_0_CCU_RD_STREAM_0_HIGHADDR 0x406ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_CCU_RD_STREAM_0 */
#define XPAR_CCU_RD_STREAM_0_BASEADDR 0x4060000
#define XPAR_CCU_RD_STREAM_0_HIGHADDR 0x406ffff

/* Definitions for peripheral PMCBRIDGE_0_CCU_WR_STREAM_0 */
#define XPAR_PMCBRIDGE_0_CCU_WR_STREAM_0_BASEADDR 0x4070000
#define XPAR_PMCBRIDGE_0_CCU_WR_STREAM_0_HIGHADDR 0x407ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_CCU_WR_STREAM_0 */
#define XPAR_CCU_WR_STREAM_0_BASEADDR 0x4070000
#define XPAR_CCU_WR_STREAM_0_HIGHADDR 0x407ffff

/* Definitions for peripheral PMCBRIDGE_0_PLM_CONFIG_0 */
#define XPAR_PMCBRIDGE_0_PLM_CONFIG_0_BASEADDR 0x4020000
#define XPAR_PMCBRIDGE_0_PLM_CONFIG_0_HIGHADDR 0x402ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PLM_CONFIG_0 */
#define XPAR_PLM_CONFIG_0_BASEADDR 0x4020000
#define XPAR_PLM_CONFIG_0_HIGHADDR 0x402ffff

/* Definitions for peripheral PMCBRIDGE_0_PMCL_EFUSE_0 */
#define XPAR_PMCBRIDGE_0_PMCL_EFUSE_0_BASEADDR 0x4160000
#define XPAR_PMCBRIDGE_0_PMCL_EFUSE_0_HIGHADDR 0x416ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_EFUSE_0 */
#define XPAR_PMCL_EFUSE_0_BASEADDR 0x4160000
#define XPAR_PMCL_EFUSE_0_HIGHADDR 0x416ffff

/* Definitions for peripheral PMCBRIDGE_0_PMCL_GLOBAL_0 */
#define XPAR_PMCBRIDGE_0_PMCL_GLOBAL_0_BASEADDR 0x40a0000
#define XPAR_PMCBRIDGE_0_PMCL_GLOBAL_0_HIGHADDR 0x40bffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_GLOBAL_0 */
#define XPAR_PMCL_GLOBAL_0_BASEADDR 0x40a0000
#define XPAR_PMCL_GLOBAL_0_HIGHADDR 0x40bffff

/* Definitions for peripheral PMCBRIDGE_0_PMCL_PUF_0 */
#define XPAR_PMCBRIDGE_0_PMCL_PUF_0_BASEADDR 0x4080000
#define XPAR_PMCBRIDGE_0_PMCL_PUF_0_HIGHADDR 0x408ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_PUF_0 */
#define XPAR_PMCL_PUF_0_BASEADDR 0x4080000
#define XPAR_PMCL_PUF_0_HIGHADDR 0x408ffff

/* Definitions for peripheral PMCBRIDGE_0_PMCL_SHA3_0 */
#define XPAR_PMCBRIDGE_0_PMCL_SHA3_0_BASEADDR 0x4100000
#define XPAR_PMCBRIDGE_0_PMCL_SHA3_0_HIGHADDR 0x410ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_SHA3_0 */
#define XPAR_PMCL_SHA3_0_BASEADDR 0x4100000
#define XPAR_PMCL_SHA3_0_HIGHADDR 0x410ffff

/* Definitions for peripheral PMCBRIDGE_0_PMCL_SLAVE_BOOT_0 */
#define XPAR_PMCBRIDGE_0_PMCL_SLAVE_BOOT_0_BASEADDR 0x4110000
#define XPAR_PMCBRIDGE_0_PMCL_SLAVE_BOOT_0_HIGHADDR 0x411ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_SLAVE_BOOT_0 */
#define XPAR_PMCL_SLAVE_BOOT_0_BASEADDR 0x4110000
#define XPAR_PMCL_SLAVE_BOOT_0_HIGHADDR 0x411ffff

/* Definitions for peripheral PMCBRIDGE_0_PMCL_TAP_0 */
#define XPAR_PMCBRIDGE_0_PMCL_TAP_0_BASEADDR 0x40c0000
#define XPAR_PMCBRIDGE_0_PMCL_TAP_0_HIGHADDR 0x40dffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_TAP_0 */
#define XPAR_PMCL_TAP_0_BASEADDR 0x40c0000
#define XPAR_PMCL_TAP_0_HIGHADDR 0x40dffff

/* Definitions for peripheral PMCBRIDGE_0_PMCL_AES_0 */
#define XPAR_PMCBRIDGE_0_PMCL_AES_0_BASEADDR 0x40f0000
#define XPAR_PMCBRIDGE_0_PMCL_AES_0_HIGHADDR 0x40fffff

/* Canonical definitions for peripheral PMCBRIDGE_0_PMCL_AES_0 */
#define XPAR_PMCL_AES_0_BASEADDR 0x40f0000
#define XPAR_PMCL_AES_0_HIGHADDR 0x40fffff

/* Definitions for peripheral PMCBRIDGE_0_RV_IOMODULE_0 */
#define XPAR_PMCBRIDGE_0_RV_IOMODULE_0_BASEADDR 0x4040000
#define XPAR_PMCBRIDGE_0_RV_IOMODULE_0_HIGHADDR 0x4040fff

/* Canonical definitions for peripheral PMCBRIDGE_0_RV_IOMODULE_0 */
#define XPAR_RV_IOMODULE_0_BASEADDR 0x4040000
#define XPAR_RV_IOMODULE_0_HIGHADDR 0x4040fff

/* Definitions for peripheral PMCBRIDGE_0_RV_RAM_DATA_ECC_CTRL_0 */
#define XPAR_PMCBRIDGE_0_RV_RAM_DATA_ECC_CTRL_0_BASEADDR 0x4042000
#define XPAR_PMCBRIDGE_0_RV_RAM_DATA_ECC_CTRL_0_HIGHADDR 0x4042fff

/* Canonical definitions for peripheral PMCBRIDGE_0_RV_RAM_DATA_ECC_CTRL_0 */
#define XPAR_RV_RAM_DATA_ECC_CTRL_0_BASEADDR 0x4042000
#define XPAR_RV_RAM_DATA_ECC_CTRL_0_HIGHADDR 0x4042fff

/* Definitions for peripheral PMCBRIDGE_0_RV_RAM_INSTR_ECC_CTRL_0 */
#define XPAR_PMCBRIDGE_0_RV_RAM_INSTR_ECC_CTRL_0_BASEADDR 0x4041000
#define XPAR_PMCBRIDGE_0_RV_RAM_INSTR_ECC_CTRL_0_HIGHADDR 0x4041fff

/* Canonical definitions for peripheral PMCBRIDGE_0_RV_RAM_INSTR_ECC_CTRL_0 */
#define XPAR_RV_RAM_INSTR_ECC_CTRL_0_BASEADDR 0x4041000
#define XPAR_RV_RAM_INSTR_ECC_CTRL_0_HIGHADDR 0x4041fff

/* Definitions for peripheral PMCBRIDGE_0_SLAVE_BOOT_STREAM_0 */
#define XPAR_PMCBRIDGE_0_SLAVE_BOOT_STREAM_0_BASEADDR 0x4050000
#define XPAR_PMCBRIDGE_0_SLAVE_BOOT_STREAM_0_HIGHADDR 0x405ffff

/* Canonical definitions for peripheral PMCBRIDGE_0_SLAVE_BOOT_STREAM_0 */
#define XPAR_SLAVE_BOOT_STREAM_0_BASEADDR 0x4050000
#define XPAR_SLAVE_BOOT_STREAM_0_HIGHADDR 0x405ffff

/*  BOARD definition */
#define XPS_BOARD_SCU35

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x7fff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 1
#define XPAR_MICROBLAZE_FPU_EXCEPTION 1
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 1
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 1
#define XPAR_MICROBLAZE_EXCEPTIONS_IN_DELAY_SLOTS 1
#define XPAR_MICROBLAZE_FREQ 50000000
#define XPAR_MICROBLAZE_USE_MSR_INSTR 1
#define XPAR_MICROBLAZE_D_CACHE_LINE_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_D_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_I_CACHE_LINE_SIZE 32
#define XPAR_MICROBLAZE_I_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 10
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 1
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 10
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 8
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_TIMEBASE_FREQUENCY 50000000
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 8
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 1
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER2 0
#define XPAR_MICROBLAZE_RESET_MSR 0
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_USE_BARREL 1
#define XPAR_MICROBLAZE_USE_DCACHE 1
#define XPAR_MICROBLAZE_USE_DIV 1
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_FPU 1
#define XPAR_MICROBLAZE_USE_HW_MUL 1
#define XPAR_MICROBLAZE_USE_ICACHE 1
#define XPAR_MICROBLAZE_USE_INTERRUPT 1
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 1
#define XPAR_MICROBLAZE_D_CACHE_BASEADDR 2147483648
#define XPAR_MICROBLAZE_D_CACHE_HIGHADDR 2155872255
#define XPAR_MICROBLAZE_I_CACHE_BASEADDR 2147483648
#define XPAR_MICROBLAZE_I_CACHE_HIGHADDR 2155872255
#define XPAR_MICROBLAZE_REG 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 50000000

#define XPAR_MICROBLAZE_DDR_RESERVE_SA 0

#define XPAR_MICROBLAZE_ADDR_SIZE 32

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "xcsu35p"

#endif  /* end of protection macro */