// SPDX-FileCopyrightText: 2026 Glen Lowe
// SPDX-License-Identifier: Apache-2.0
`timescale 1ns/1ps

module hyperbus_phy_xilinx #(
    parameter int PHY_IO_STYLE = 0,
    parameter int PHY_FAMILY = 0
) (
    input  wire        i_hb_clk_200,
    input  wire        i_hb_clk_200_gated,
    input  wire        i_axi_aclk,
    input  wire        i_axi_aresetn,
    input  wire        i_ref_clk_300,
    input  wire        i_idelayctrl_rst,
    input  wire        i_idelayctrl_rst_req,
    input  wire        i_odelay_rst_req,
    input  wire        i_rwds_idelay_rst_req,
    input  wire        i_hb_clk_200_samp_90,
    input  wire        i_iddre1_rst,
    input  wire        i_hb_rstn,
    output wire        o_hb_ck_p,
    output wire        o_hb_ck_n,
    inout  wire        io_hb_rwds,
    inout  wire [7:0]  io_hb_dq,
    input  wire [7:0]  i_dq_t,
    input  wire [7:0]  i_dq_o_d1,
    input  wire [7:0]  i_dq_o_d2,
    output logic [7:0] o_dq_q1,
    output logic [7:0] o_dq_q2,
    input  wire        i_rwds_t,
    input  wire        i_rwds_o_d1,
    input  wire        i_rwds_o_d2,
    output wire        o_rwds_q1,
    output wire        o_rwds_q2,
    input  wire        i_odly_en_vtc,
    input  wire        i_odly_ce,
    input  wire        i_odly_inc,
    input  wire        i_odly_load,
    input  wire [8:0]  i_odly_cntvaluein,
    input  wire        i_rwds_idly_en_vtc,
    input  wire        i_rwds_idly_ce,
    input  wire        i_rwds_idly_inc,
    input  wire        i_rwds_idly_load,
    input  wire [8:0]  i_rwds_idly_cntvaluein,
    input  wire [7:0]  i_dq_idly_en_vtc,
    input  wire [7:0]  i_dq_idly_ce,
    input  wire [7:0]  i_dq_idly_inc,
    input  wire [7:0]  i_dq_idly_load,
    input  wire [71:0] i_dq_idly_cntvaluein,
    output wire [71:0] o_dq_idly_cntvalueout,
    output wire [8:0]  o_rwds_idly_cntvalueout,
    output wire [8:0]  o_odly_cntvalueout,
    output wire        o_idelayctrl_rdy_axi,
    output logic [15:0] o_dq
);

    localparam int PHY_FAMILY_ULTRASCALE_PLUS = 0;
    localparam int PHY_FAMILY_7SERIES         = 1;

    generate
        if (PHY_FAMILY == PHY_FAMILY_7SERIES) begin : g_phy_7series
            hyperbus_phy_xilinx_7series #(
                .PHY_IO_STYLE           (          PHY_IO_STYLE)
            ) u_phy_impl (
                .i_hb_clk_200            (            i_hb_clk_200),
                .i_hb_clk_200_gated      (      i_hb_clk_200_gated),
                .i_axi_aclk              (              i_axi_aclk),
                .i_axi_aresetn           (           i_axi_aresetn),
                .i_ref_clk_300           (           i_ref_clk_300),
                .i_idelayctrl_rst        (        i_idelayctrl_rst),
                .i_idelayctrl_rst_req    (    i_idelayctrl_rst_req),
                .i_odelay_rst_req        (        i_odelay_rst_req),
                .i_rwds_idelay_rst_req   (   i_rwds_idelay_rst_req),
                .i_hb_clk_200_samp_90    (    i_hb_clk_200_samp_90),
                .i_iddre1_rst            (            i_iddre1_rst),
                .i_hb_rstn               (               i_hb_rstn),
                .o_hb_ck_p               (               o_hb_ck_p),
                .o_hb_ck_n               (               o_hb_ck_n),
                .io_hb_rwds              (              io_hb_rwds),
                .io_hb_dq                (                io_hb_dq),
                .i_dq_t                  (                  i_dq_t),
                .i_dq_o_d1               (               i_dq_o_d1),
                .i_dq_o_d2               (               i_dq_o_d2),
                .o_dq_q1                 (                 o_dq_q1),
                .o_dq_q2                 (                 o_dq_q2),
                .i_rwds_t                (                i_rwds_t),
                .i_rwds_o_d1             (             i_rwds_o_d1),
                .i_rwds_o_d2             (             i_rwds_o_d2),
                .o_rwds_q1               (               o_rwds_q1),
                .o_rwds_q2               (               o_rwds_q2),
                .i_odly_en_vtc           (           i_odly_en_vtc),
                .i_odly_ce               (               i_odly_ce),
                .i_odly_inc              (              i_odly_inc),
                .i_odly_load             (             i_odly_load),
                .i_odly_cntvaluein       (       i_odly_cntvaluein),
                .i_rwds_idly_en_vtc      (      i_rwds_idly_en_vtc),
                .i_rwds_idly_ce          (          i_rwds_idly_ce),
                .i_rwds_idly_inc         (         i_rwds_idly_inc),
                .i_rwds_idly_load        (        i_rwds_idly_load),
                .i_rwds_idly_cntvaluein  (  i_rwds_idly_cntvaluein),
                .i_dq_idly_en_vtc        (        i_dq_idly_en_vtc),
                .i_dq_idly_ce            (            i_dq_idly_ce),
                .i_dq_idly_inc           (           i_dq_idly_inc),
                .i_dq_idly_load          (          i_dq_idly_load),
                .i_dq_idly_cntvaluein    (    i_dq_idly_cntvaluein),
                .o_dq_idly_cntvalueout   (   o_dq_idly_cntvalueout),
                .o_rwds_idly_cntvalueout ( o_rwds_idly_cntvalueout),
                .o_odly_cntvalueout      (      o_odly_cntvalueout),
                .o_idelayctrl_rdy_axi    (    o_idelayctrl_rdy_axi),
                .o_dq                    (                    o_dq)
            );
        end else begin : g_phy_ultrascale_plus
            hyperbus_phy_xilinx_usplus #(
                .PHY_IO_STYLE           (          PHY_IO_STYLE)
            ) u_phy_impl (
                .i_hb_clk_200            (            i_hb_clk_200),
                .i_hb_clk_200_gated      (      i_hb_clk_200_gated),
                .i_axi_aclk              (              i_axi_aclk),
                .i_axi_aresetn           (           i_axi_aresetn),
                .i_ref_clk_300           (           i_ref_clk_300),
                .i_idelayctrl_rst        (        i_idelayctrl_rst),
                .i_idelayctrl_rst_req    (    i_idelayctrl_rst_req),
                .i_odelay_rst_req        (        i_odelay_rst_req),
                .i_rwds_idelay_rst_req   (   i_rwds_idelay_rst_req),
                .i_hb_clk_200_samp_90    (    i_hb_clk_200_samp_90),
                .i_iddre1_rst            (            i_iddre1_rst),
                .i_hb_rstn               (               i_hb_rstn),
                .o_hb_ck_p               (               o_hb_ck_p),
                .o_hb_ck_n               (               o_hb_ck_n),
                .io_hb_rwds              (              io_hb_rwds),
                .io_hb_dq                (                io_hb_dq),
                .i_dq_t                  (                  i_dq_t),
                .i_dq_o_d1               (               i_dq_o_d1),
                .i_dq_o_d2               (               i_dq_o_d2),
                .o_dq_q1                 (                 o_dq_q1),
                .o_dq_q2                 (                 o_dq_q2),
                .i_rwds_t                (                i_rwds_t),
                .i_rwds_o_d1             (             i_rwds_o_d1),
                .i_rwds_o_d2             (             i_rwds_o_d2),
                .o_rwds_q1               (               o_rwds_q1),
                .o_rwds_q2               (               o_rwds_q2),
                .i_odly_en_vtc           (           i_odly_en_vtc),
                .i_odly_ce               (               i_odly_ce),
                .i_odly_inc              (              i_odly_inc),
                .i_odly_load             (             i_odly_load),
                .i_odly_cntvaluein       (       i_odly_cntvaluein),
                .i_rwds_idly_en_vtc      (      i_rwds_idly_en_vtc),
                .i_rwds_idly_ce          (          i_rwds_idly_ce),
                .i_rwds_idly_inc         (         i_rwds_idly_inc),
                .i_rwds_idly_load        (        i_rwds_idly_load),
                .i_rwds_idly_cntvaluein  (  i_rwds_idly_cntvaluein),
                .i_dq_idly_en_vtc        (        i_dq_idly_en_vtc),
                .i_dq_idly_ce            (            i_dq_idly_ce),
                .i_dq_idly_inc           (           i_dq_idly_inc),
                .i_dq_idly_load          (          i_dq_idly_load),
                .i_dq_idly_cntvaluein    (    i_dq_idly_cntvaluein),
                .o_dq_idly_cntvalueout   (   o_dq_idly_cntvalueout),
                .o_rwds_idly_cntvalueout ( o_rwds_idly_cntvalueout),
                .o_odly_cntvalueout      (      o_odly_cntvalueout),
                .o_idelayctrl_rdy_axi    (    o_idelayctrl_rdy_axi),
                .o_dq                    (                    o_dq)
            );
        end
    endgenerate

endmodule
