// SPDX-FileCopyrightText: 2026 Glen Lowe
// SPDX-License-Identifier: Apache-2.0
`timescale 1ns/1ps

module hyperbus_fifo_bank_xilinx #(
    parameter int CMD_W = 75
) (
    input  wire             i_axi_aclk,
    input  wire             i_axi_aresetn,
    input  wire             i_hb_clk_200,
    input  wire             i_hb_rstn,

    input  wire [CMD_W-1:0] i_cmd_fifo_din,
    input  wire             i_cmd_fifo_wr_en,
    output wire             o_cmd_fifo_full,
    output wire [CMD_W-1:0] o_cmd_fifo_dout,
    input  wire             i_cmd_fifo_rd_en,
    output wire             o_cmd_fifo_empty,
    output wire             o_cmd_fifo_dout_valid,

    input  wire [35:0]      i_wr_fifo_din,
    input  wire             i_wr_fifo_wr_en,
    output wire             o_wr_fifo_full,
    output wire             o_wr_fifo_prog_full,
    output wire [35:0]      o_wr_fifo_dout,
    input  wire             i_wr_fifo_rd_en,
    output wire             o_wr_fifo_empty,
    output wire             o_wr_fifo_dout_valid,

    input  wire [31:0]      i_rd_fifo_din,
    input  wire             i_rd_fifo_wr_en,
    output wire             o_rd_fifo_full,
    output wire             o_rd_fifo_prog_full,
    output wire [31:0]      o_rd_fifo_dout,
    input  wire             i_rd_fifo_rd_en,
    output wire             o_rd_fifo_empty,
    output wire             o_rd_fifo_dout_valid,

    input  wire [31:0]      i_axil_rsp_fifo_din,
    input  wire             i_axil_rsp_fifo_wr_en,
    output wire             o_axil_rsp_fifo_full,
    output wire [31:0]      o_axil_rsp_fifo_dout,
    input  wire             i_axil_rsp_fifo_rd_en,
    output wire             o_axil_rsp_fifo_empty,
    output wire             o_axil_rsp_fifo_dout_valid
);

    wire fifo_rst_axi_wr = ~i_axi_aresetn;
    wire fifo_rst_hb_wr  = ~i_hb_rstn;

    xpm_fifo_async #(
        .DOUT_RESET_VALUE("0"),
        .ECC_MODE("no_ecc"),
        .FIFO_MEMORY_TYPE("block"),
        .FIFO_READ_LATENCY(1),
        .FIFO_WRITE_DEPTH(32),
        .FULL_RESET_VALUE(0),
        .PROG_EMPTY_THRESH(10),
        .PROG_FULL_THRESH(10),
        .RD_DATA_COUNT_WIDTH(6),
        .READ_DATA_WIDTH(CMD_W),
        .READ_MODE("std"),
        .USE_ADV_FEATURES("1002"),
        .WAKEUP_TIME(0),
        .WRITE_DATA_WIDTH(CMD_W),
        .WR_DATA_COUNT_WIDTH(6)
    ) u_cmd_fifo (
        .rst(fifo_rst_axi_wr),
        .wr_clk(i_axi_aclk),
        .rd_clk(i_hb_clk_200),
        .din(i_cmd_fifo_din),
        .wr_en(i_cmd_fifo_wr_en),
        .full(o_cmd_fifo_full),
        .dout(o_cmd_fifo_dout),
        .rd_en(i_cmd_fifo_rd_en),
        .empty(o_cmd_fifo_empty),
        .data_valid(o_cmd_fifo_dout_valid),
        .almost_empty(),
        .almost_full(),
        .dbiterr(),
        .injectdbiterr(1'b0),
        .injectsbiterr(1'b0),
        .overflow(),
        .prog_empty(),
        .prog_full(),
        .rd_data_count(),
        .rd_rst_busy(),
        .sbiterr(),
        .underflow(),
        .wr_ack(),
        .wr_data_count(),
        .wr_rst_busy(),
        .sleep(1'b0)
    );

    xpm_fifo_async #(
        .DOUT_RESET_VALUE("0"),
        .ECC_MODE("no_ecc"),
        .FIFO_MEMORY_TYPE("block"),
        .FIFO_READ_LATENCY(0),
        .FIFO_WRITE_DEPTH(256),
        .FULL_RESET_VALUE(0),
        .PROG_EMPTY_THRESH(10),
        .PROG_FULL_THRESH(240),
        .RD_DATA_COUNT_WIDTH(9),
        .READ_DATA_WIDTH(36),
        .READ_MODE("fwft"),
        .USE_ADV_FEATURES("1000"),
        .WAKEUP_TIME(0),
        .WRITE_DATA_WIDTH(36),
        .WR_DATA_COUNT_WIDTH(9)
    ) u_wr_fifo (
        .rst(fifo_rst_axi_wr),
        .wr_clk(i_axi_aclk),
        .rd_clk(i_hb_clk_200),
        .din(i_wr_fifo_din),
        .wr_en(i_wr_fifo_wr_en),
        .full(o_wr_fifo_full),
        .dout(o_wr_fifo_dout),
        .rd_en(i_wr_fifo_rd_en),
        .empty(o_wr_fifo_empty),
        .data_valid(o_wr_fifo_dout_valid),
        .almost_empty(),
        .almost_full(),
        .dbiterr(),
        .injectdbiterr(1'b0),
        .injectsbiterr(1'b0),
        .overflow(),
        .prog_empty(),
        .prog_full(o_wr_fifo_prog_full),
        .rd_data_count(),
        .rd_rst_busy(),
        .sbiterr(),
        .underflow(),
        .wr_ack(),
        .wr_data_count(),
        .wr_rst_busy(),
        .sleep(1'b0)
    );

    xpm_fifo_async #(
        .DOUT_RESET_VALUE("0"),
        .ECC_MODE("no_ecc"),
        .FIFO_MEMORY_TYPE("block"),
        .FIFO_READ_LATENCY(0),
        .FIFO_WRITE_DEPTH(256),
        .FULL_RESET_VALUE(0),
        .PROG_EMPTY_THRESH(10),
        .PROG_FULL_THRESH(240),
        .RD_DATA_COUNT_WIDTH(9),
        .READ_DATA_WIDTH(32),
        .READ_MODE("fwft"),
        .USE_ADV_FEATURES("1002"),
        .WAKEUP_TIME(0),
        .WRITE_DATA_WIDTH(32),
        .WR_DATA_COUNT_WIDTH(9)
    ) u_rd_fifo (
        .rst(fifo_rst_hb_wr),
        .wr_clk(i_hb_clk_200),
        .rd_clk(i_axi_aclk),
        .din(i_rd_fifo_din),
        .wr_en(i_rd_fifo_wr_en),
        .full(o_rd_fifo_full),
        .dout(o_rd_fifo_dout),
        .rd_en(i_rd_fifo_rd_en),
        .empty(o_rd_fifo_empty),
        .data_valid(o_rd_fifo_dout_valid),
        .almost_empty(),
        .almost_full(),
        .dbiterr(),
        .injectdbiterr(1'b0),
        .injectsbiterr(1'b0),
        .overflow(),
        .prog_empty(),
        .prog_full(o_rd_fifo_prog_full),
        .rd_data_count(),
        .rd_rst_busy(),
        .sbiterr(),
        .underflow(),
        .wr_ack(),
        .wr_data_count(),
        .wr_rst_busy(),
        .sleep(1'b0)
    );

    xpm_fifo_async #(
        .DOUT_RESET_VALUE("0"),
        .ECC_MODE("no_ecc"),
        .FIFO_MEMORY_TYPE("block"),
        .FIFO_READ_LATENCY(1),
        .FIFO_WRITE_DEPTH(32),
        .FULL_RESET_VALUE(0),
        .PROG_EMPTY_THRESH(10),
        .PROG_FULL_THRESH(10),
        .RD_DATA_COUNT_WIDTH(6),
        .READ_DATA_WIDTH(32),
        .READ_MODE("std"),
        .USE_ADV_FEATURES("1000"),
        .WAKEUP_TIME(0),
        .WRITE_DATA_WIDTH(32),
        .WR_DATA_COUNT_WIDTH(6)
    ) u_axil_rsp_fifo (
        .rst(fifo_rst_hb_wr),
        .wr_clk(i_hb_clk_200),
        .rd_clk(i_axi_aclk),
        .din(i_axil_rsp_fifo_din),
        .wr_en(i_axil_rsp_fifo_wr_en),
        .full(o_axil_rsp_fifo_full),
        .dout(o_axil_rsp_fifo_dout),
        .rd_en(i_axil_rsp_fifo_rd_en),
        .empty(o_axil_rsp_fifo_empty),
        .data_valid(o_axil_rsp_fifo_dout_valid),
        .almost_empty(),
        .almost_full(),
        .dbiterr(),
        .injectdbiterr(1'b0),
        .injectsbiterr(1'b0),
        .overflow(),
        .prog_empty(),
        .prog_full(),
        .rd_data_count(),
        .rd_rst_busy(),
        .sbiterr(),
        .underflow(),
        .wr_ack(),
        .wr_data_count(),
        .wr_rst_busy(),
        .sleep(1'b0)
    );

endmodule
